[package]
name = "stego_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.24"
sha2 = "0.10"
aes-gcm = "0.10"
rand = "0.8"
log = "0.4"
env_logger = "0.10"
rusqlite = { version = "0.29.0", features = ["bundled"] }
png = "^0.17"